language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: andrawaag
  password:
    secure: B6rzZvecIU/l0oEhpC/zPZgOwBlHdoGpLWlmGxV43RfydWIMvF3pknstzyYEkngrZmYM7yqUCMwVu+bjsThWsZ3SOX+bxI8tZ+zr2V/n8uTwwFYaXjzWUaStGp0vHGEDilgE0Q1nlL8TSg23YVfekbCHhdIlrANtJ1Xb2paEuq933eZ16O3mmgVz82YQbNNEHLgabxoQkBT/c/Bohvs/h8vGpCEPLrz7trFnvw35cOba/Z56SIa6hZ4MfYICNXNKQpONtrxl/BUXYD/xRy08nso2zAlh/uITGD40xaVM4p9XNtOd2sjFNqcNwGSkf0G0IRsFxvofb6LfRhqLRjjfoca2lmOioSsUbIWKNl+JvJSV+eCRbaRGeeRjxjBY90Rja9XurslQGRj/QDKdWxgFMYhJLKIYYsz4ox4Xuj2h1+NhaJqLpC3Z/26rKkkxI9jtkvnnjRFxRnT9svhFDflNp571oelyiyizXTo6op0K88RdFDxOax/iQgI0Qq5Q7OvyuQEgNQiOeDUU5Tm4ItmOqFM6zbixRuTHyOMPmhs1aaSXwwn4pDdjj8QZzH4VdMsmZZAgoTWQyMS2gWNPG5g3UnaqgDxGhctZld1AbcYCu5nTxYHIj6cXCOLGgjgRri/TuOGD+6ocoLNkOUY6oWnskhd8bgxmTKuhVcr8YmBP9WY=
  on:
    tags: true
